### PR TITLE
done reviewing and commenting

### PR DESCRIPTION
**Pull request by TheKinng96**
Hi Arvind, this pull request will replace your project by my edited version. Usually we will have development branch in real project tho, so all the changes will go to the development instead of master like now. I just added some codes and comments on your project, it will not break your things, so no worries. I left messages mainly on the readme and please have a look on it, also comments on the index.html about my changes. Peace~

### CODE REVIEW

**Comment by Arvind644** [comment]
Thanks a lot for doing a review and make this project better. I am really appreciate your efforts and love the changes you have made.

**Comment by TheKinng96** [comment]
loll you just merged it tho haha

**Comment by TheKinng96** [comment]
just take a look at my comments hope it helps you on the future development

**Comment by Arvind644** [comment]
Ok , I am looking into that

**Comment by TheKinng96** [comment]
i wanna go and find open source to help haha
the process is like this, folk the repo, do your editing and pull request
you will get used to it

**Comment by Arvind644** [comment]
I think I have to spent more time in github to understand it bettter

**Comment by TheKinng96** [comment]
sure thing take your time, coding is amazing
slow is ok, at least we are moving haha
ganbateh

**Pull request merged**
